USE [master]
GO
/****** Object:  Database [Sklad]    Script Date: 31.01.2022 12:14:24 ******/
CREATE DATABASE [Sklad]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sklad', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Sklad.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sklad_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Sklad_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Sklad] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sklad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sklad] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sklad] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sklad] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sklad] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sklad] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sklad] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sklad] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sklad] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sklad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sklad] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sklad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sklad] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sklad] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sklad] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sklad] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sklad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sklad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sklad] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sklad] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sklad] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sklad] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sklad] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sklad] SET RECOVERY FULL 
GO
ALTER DATABASE [Sklad] SET  MULTI_USER 
GO
ALTER DATABASE [Sklad] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sklad] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sklad] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sklad] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sklad] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Sklad', N'ON'
GO
ALTER DATABASE [Sklad] SET QUERY_STORE = OFF
GO
USE [Sklad]
GO
/****** Object:  Table [dbo].[Поставщики]    Script Date: 31.01.2022 12:14:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Поставщики](
	[код_поставщика] [int] NOT NULL,
	[наименование] [text] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ПриходТовара]    Script Date: 31.01.2022 12:14:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ПриходТовара](
	[код_прихода] [int] NOT NULL,
	[код_склад_един] [int] NOT NULL,
	[дата_прихода] [date] NULL,
	[объём] [nchar](10) NOT NULL,
	[срок_годности] [date] NULL,
 CONSTRAINT [PK_ПриходТовара] PRIMARY KEY CLUSTERED 
(
	[код_прихода] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[СкладскиеЕденицы]    Script Date: 31.01.2022 12:14:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[СкладскиеЕденицы](
	[код_единцы] [int] NOT NULL,
	[код_товара] [int] NOT NULL,
	[код_поставщика] [int] NOT NULL,
	[цена] [money] NULL,
	[един_измер] [nchar](10) NOT NULL,
	[сум_кол_тов] [nchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Товары]    Script Date: 31.01.2022 12:14:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Товары](
	[код_товара] [int] NOT NULL,
	[наименование] [text] NOT NULL,
 CONSTRAINT [PK_Товары] PRIMARY KEY CLUSTERED 
(
	[код_товара] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[Поставщики] ([код_поставщика], [наименование]) VALUES (444, N'pr')
GO
INSERT [dbo].[Поставщики] ([код_поставщика], [наименование]) VALUES (445, N'bl')
GO
INSERT [dbo].[СкладскиеЕденицы] ([код_единцы], [код_товара], [код_поставщика], [цена], [един_измер], [сум_кол_тов]) VALUES (123, 221, 444, 1000.0000, N'кг        ', N'2         ')
GO
INSERT [dbo].[СкладскиеЕденицы] ([код_единцы], [код_товара], [код_поставщика], [цена], [един_измер], [сум_кол_тов]) VALUES (124, 222, 444, 800.0000, N'кг        ', N'3         ')
GO
USE [master]
GO
ALTER DATABASE [Sklad] SET  READ_WRITE 
GO
